### PR TITLE
updated documentation

### PR DESCRIPTION
**Pull request by JoergBruenner**
### Description

added in use case sectio samples how to import a bom and how to use EPSS

### Checklist

- [x] I have read and understand the [contributing guidelines](https://github.com/DependencyTrack/dependency-track/blob/github-templates/CONTRIBUTING.md#pull-requests)
- [ ] This PR fixes a defect, and I have provided tests to verify that the fix is effective
- [ ] This PR implements an enhancement, and I have provided tests to verify that it works as intended
- [ ] This PR introduces changes to the database model, and I have added corresponding [update logic](https://github.com/DependencyTrack/dependency-track/tree/master/src/main/java/org/dependencytrack/upgrade)
- [ ] This PR introduces new or alters existing behavior, and I have updated the [documentation](https://github.com/DependencyTrack/dependency-track/tree/master/docs/_docs) accordingly

### CODE REVIEW

**Comment by JoergBruenner** [comment]
Tried to resolve conflicts, cant push them ...

**Comment by stevespringett** [comment]
@nscuro Why was https://docs.dependencytrack.org/usage/usecases/ merged in? Having a structure of Usage -> Use Cases where the Use Cases page doesn't include any use cases is seriously confusing.

@JoergBruenner This page needs to be eliminated or moved to another part of the documentation. The title of the page needs to be clarified to communicate what the content is about.

**Comment by stevespringett** [comment]
Please work to correct these issues prior to the release of v4.8. If not, the page will be removed to reduce confusion.

**Comment by nscuro** [comment]
@stevespringett I believe there's value in including showcases / walkthroughs of how folks use DT to solve various, perhaps non-obvious, problems in the docs. But I see why the structure can be confusing.

We can rename this page to "Example Workflows" or "Community Usage Examples" and make it clear that the content is community-maintained.

**Comment by nscuro** [comment]
As this PR is stale and has conflicts, I'm going to close it.

@JoergBruenner I have made some changes to what you proposed in this PR, I'd appreciate a review from you if #2403 still reflects what you wanted to bring across. Thanks!

**Pull request closed without merging**
