### PR TITLE
Adding basic authentication for analyzer

### PR DESCRIPTION
**Pull request by Marx314**
#881 might come handy.

I wasn't sure about the move of unirestGet to abstract, and the complexity level is exploding for the MavenMetaAnalyzer.

The API accept the new fields, I don't know how to update the UI.

### CODE REVIEW

**Comment by stevespringett** [comment]
Thanks for the PR. I think we need to store the credentials using ConfigProperty so that we get the benefit of encryption at rest.

**Comment by Marx314** [comment]
@stevespringett humm I'm not exactly sure how it would be easily possible without doing some fairly large assumption.
There would be only 1 set of credentials that would be sent to all type of internal repository?
1 set par type of repository?

**Comment by AbdelHajou** [comment]
Hi @Marx314 , are you still working on this?

**Comment by Marx314** [comment]
@AbdelHajou not really since I didn't get any additional details.

**Pull request closed without merging**
