### PR TITLE
Fix `NullPointerException` when updating a project

### LINKED ISSUE #2317: Updating a project fails when its active status is `null`
### Current Behavior

If the active status of a project is `null` and someone tries to update that project, a `NullPointerException` will be thrown because that case is currently not handled.

### Steps to Reproduce

Adding this test to `ProjectResourceTest` and executing it will throw a `NullPointerException`:

```
@Test
  public void updateProjectTestIsActiveEqualsNull() {
      Project project = qm.createProject("ABC", null, "1.0", null, null, null, true, false);
      project.setDescription("Test project");
      project.setActive(null);
      Assert.assertNull(project.isActive());
      Response response = target(V1_PROJECT)
              .request()
              .header(X_API_KEY, apiKey)
              .post(Entity.entity(project, MediaType.APPLICATION_JSON));
      Assert.assertEquals(200, response.getStatus(), 0);
      JsonObject json = parseJsonObject(response);
      Assert.assertNotNull(json);
      Assert.assertEquals("ABC", json.getString("name"));
      Assert.assertEquals("1.0", json.getString("version"));
      Assert.assertEquals("Test project", json.getString("description"));
      Assert.assertTrue(json.getBoolean("active"));
  }
```

### Expected Behavior

It should be checked if the active status of a project is `null` and no `NullPointerException` should be thrown.

### Dependency-Track Version

4.7.0

### Dependency-Track Distribution

Container Image

### Database Server

H2

### Database Server Version

_No response_

### Browser

N/A

### Checklist

- [X] I have read and understand the [contributing guidelines](https://github.com/DependencyTrack/dependency-track/blob/master/CONTRIBUTING.md#filing-issues)
- [X] I have checked the [existing issues](https://github.com/DependencyTrack/dependency-track/issues) for whether this defect was already reported

### PR DESCRIPTION
**Pull request by rbt-mm**
### Description

If the active status of a project is `null` and someone tries to update that project, a `NullPointerException` will be thrown because that case is currently not handled.

This PR checks if the active status of a project is `null` when trying to update the project, and handles the case, resulting in no `NullPointerException` being thrown.

### Addressed Issue

Closes #2317

### Checklist

- [x] I have read and understand the [contributing guidelines](https://github.com/DependencyTrack/dependency-track/blob/github-templates/CONTRIBUTING.md#pull-requests)
- [x] This PR fixes a defect, and I have provided tests to verify that the fix is effective
~- [ ] This PR implements an enhancement, and I have provided tests to verify that it works as intended~
~- [ ] This PR introduces changes to the database model, and I have added corresponding [update logic](https://github.com/DependencyTrack/dependency-track/tree/master/src/main/java/org/dependencytrack/upgrade)~
~- [ ] This PR introduces new or alters existing behavior, and I have updated the [documentation](https://github.com/DependencyTrack/dependency-track/tree/master/docs/_docs) accordingly~

### CODE REVIEW

**Comment by valentijnscholten** [comment]
if you run a project wide search for `isActive()` there are 2 or 3 other places which could do with the same safeguard.

**Comment by rbt-mm** [comment]
Thanks for noticing, I think that every `isActive()` should be handled correctly now.

**Review by nscuro — APPROVED** [review]
Thanks @rbt-mm and @valentijnscholten! 🙌

**Comment by valentijnscholten** [comment]
@nscuro This started occurring out of nowhere on my instances. There might be some codepaths in 4.7.0 that somehow set a null value in the database. So a onetime SQL query to fix those values might not be a structural solution. Any chance we can get a 4.7.1?

**Comment by nscuro** [comment]
@valentijnscholten We're looking into bundling multiple of such annoyances into a bugfix release right now. I've seen a few similar requests now on other issues so I think it makes sense to backport more than just this.

**Comment by SaberStrat** [comment]
Any update on a patch release to help fix this? 
I'm doing a POST on the project API in several places in our CI, and this is failing now :/. Is there any workaround that I could attempt until then? A manual SQL query against the table with the missing active values?

**Comment by nscuro** [comment]
We backported this to 4.7.1, which was just released.

**Comment by SaberStrat** [comment]
Thank you very much ❤️

**Pull request merged**
