### PR TITLE
Consolidated dependency updates

### PR DESCRIPTION
**Pull request by melba-lopez**
### Description

Consolidated dependency updates

| Package | Type | Update | Change |
|---|---|---|---|
|'~mysql:mysql-connector-java '~| compile | patch | '~8.0.29 -> 8.0.33 '~|  
|org.glassfish.jaxb:jaxb-runtime (source) | compile | patch | 2.3.6 -> 2.3.8 | 
|org.postgresql:postgresql (source) | compile | minor | 42.5.1 -> 42.6.0 | 
|eclipse-temurin | stage | patch | 17.0.6_10-jre-focal -> 17.0.7_7-jre-focal | 
|com.microsoft.sqlserver:mssql-jdbc | compile | major | 11.2.3.jre17 -> 12.2.0.jre11 | 
|'~jekyll '~|   | major | '~3.8 -> 4.0 '~ | 
|'~org.eclipse.jetty:jetty-maven-plugin (source) '~| build | major | '~10.0.15 -> 11.0.15 '~| 

### Additional Details

Upgrades not compatible at this time:
- [mysql:mysql-connector-java ](#1970 )
- [org.eclipse.jetty:jetty-maven-plugin](#2727  )

Postponed:
- jekyll per https://github.com/DependencyTrack/dependency-track/pull/2725#issuecomment-1587870411 

### Checklist

- [x] I have read and understand the [contributing guidelines](../CONTRIBUTING.md#pull-requests)
- [x] This PR fixes a defect, and I have provided tests to verify that the fix is effective
- [ ] This PR implements an enhancement, and I have provided tests to verify that it works as intended
- [ ] This PR introduces changes to the database model, and I have added corresponding [update logic](https://github.com/DependencyTrack/dependency-track/tree/master/src/main/java/org/dependencytrack/upgrade)
- [ ] This PR introduces new or alters existing behavior, and I have updated the [documentation](https://github.com/DependencyTrack/dependency-track/tree/master/docs/_docs) accordingly

### CODE REVIEW

**Comment by stevespringett** [comment]
The upgrade to Jetty 11 Maven plugin will likely break development environments due to the migration of javax to jakarta. DT still relies on Jetty 10. We should likely have a dedicated story specific to the upgrade of Jetty and migration from javax to jakarta. This will impact both DT and Java Alpine.

**Comment by melba-lopez** [comment]
> d likely have a dedicated story specific to the upgrade of Jetty and migration from javax to jakarta. This will impact both DT and Java Alpine.

@stevespringett I can remove the jetty upgrade for now and make a comment inline.

**Comment by nscuro** [comment]
The Jekyll update needs to be tested by building the docs: https://github.com/DependencyTrack/dependency-track/blob/master/DEVELOPING.md#documentation

We'll also need to make sure GitHub pages continues to work.

> We should likely have a dedicated story specific to the upgrade of Jetty and migration from javax to jakarta. This will impact both DT and Java Alpine.

For Alpine there's https://github.com/stevespringett/Alpine/issues/402 already.

@melba-lopez Please make sure you sign-off your commits. If you click on "Details" of the DCO check it will show you what to do.

**Comment by melba-lopez** [comment]
> The Jekyll update needs to be tested by building the docs: https://github.com/DependencyTrack/dependency-track/blob/master/DEVELOPING.md#documentation
> 
> We'll also need to make sure GitHub pages continues to work.
**Will attempt testing it now**


> @melba-lopez Please make sure you sign-off your commits. If you click on "Details" of the DCO check it will show you what to do. **(Done)**
image

**Comment by melba-lopez** [comment]
>The Jekyll update needs to be tested by building the docs: https://github.com/DependencyTrack/dependency-track/blob/master/DEVELOPING.md#documentation

Just tested on local machine and it appears to be working.  Also, should we update this command in the docs https://github.com/DependencyTrack/dependency-track/blob/master/DEVELOPING.md#documentation

`docker run --rm -it --name jekyll -p "127.0.0.1:4000:4000" -v "$(pwd)/docs:/srv/jekyll:Z" jekyll/jekyll:4.0 jekyll serve`

image

>We'll also need to make sure GitHub pages continues to work.
I don't know how to test the github pages.   Can you point me in the right direction?

**Comment by nscuro** [comment]
> I don't know how to test the github pages. Can you point me in the right direction?

Only way I know is actually deploying it. I think you can do it in your fork such that it's available under https://melba-lopez.github.io/dependency-track. Here's how it's currently set up for us:

image

I also found this dedicated website for dependency versions in GitHub pages: https://pages.github.com/versions/

it says it's using Jekyll 3.9.3, but I am not 100% if that means depending on Jekyll 4.x will break things.

**Comment by nscuro** [comment]
@melba-lopez For the sake of moving this forward, maybe we can just drop the Jekyll update for now, and investigate on this separately?

**Comment by melba-lopez** [comment]
Sounds good to me.  @nscuro -- been out sick (myself/family) so have not had time to do much in this space.  I got back last week.  Not sure if this still is applicable given the 4.8 release that happened afterwards.  I can always add extra packages if you'd like or just use this PR as a test only.

**Comment by melba-lopez** [comment]
@nscuro once the checks pass, this should be good to go!

**Pull request closed without merging**
