### PR TITLE
Add option to test notification publisher

### PR DESCRIPTION
**Pull request by 2000rosser**
### Description
Replaced the /test/smtp endpoint to work for any of the publishers.

Front end implementation: https://github.com/DependencyTrack/frontend/pull/949

### Addressed Issue
#2924 

### Checklist

- [x] I have read and understand the [contributing guidelines](../CONTRIBUTING.md#pull-requests)
- [ ] This PR fixes a defect, and I have provided tests to verify that the fix is effective
- [x] This PR implements an enhancement, and I have provided tests to verify that it works as intended
- [ ] This PR introduces changes to the database model, and I have added corresponding [update logic](https://github.com/DependencyTrack/dependency-track/tree/master/src/main/java/org/dependencytrack/upgrade)
- [ ] This PR introduces new or alters existing behavior, and I have updated the [documentation](https://github.com/DependencyTrack/dependency-track/tree/master/docs/_docs) accordingly

### CODE REVIEW

**Review by nscuro — CHANGES_REQUESTED** [review]
I'm not sure this addresses the original feature request.

Having a test button for the email *publisher* makes sense, because DT only ever connects to a single email server, and those connection details are a global setting. 

However, for pretty much all other publishers, there is no global configuration. Instead, destination URLs are configured for each alert (see for example MS Teams, Slack, Webhook). Testing the publisher without an alert (`NotificationRule`) will not work for those.

We'd need a test functionality on the alert / `NotificationRule` level. This also means we can't use the same hardcoded `Notification`, since alerts are configured for specific levels and groups. Either we dynamically build a `Notification` object that will satisfy the alert under test, or we let users provide an entirely custom one.

**Comment by 2000rosser** [comment]
The approach I went for was to test only the destination for the selected alert rule in the setup page, which worked for the publishers I tested (Slack, MS Teams). If we want to test on the `NotificationRule` level, which approach would be preferred, letting users provide a custom `Notification` or build one that satisfies the `NotificationRule`. 

Could possibly POST the `NotificationRule` similar to [here](https://github.com/DependencyTrack/frontend/blob/0a4bdcb2e99380f28b2d9b0d178183c70558ab07/src/views/administration/notifications/Alerts.vue#L333-L363) and then either build the `Notification` that satisfies it or send a user provided one.

**Comment by nscuro** [comment]
> The approach I went for was to test only the destination for the selected alert rule in the setup page, which worked for the publishers I tested (Slack, MS Teams).

That approach is not necessarily wrong, either. But it limits the usefulness of the check a bit, since individual rules can be customized further (i.e. auth headers for *Outbound Webhook* alerts). Ideally you'd want to know whether a *specific* rule works.

> Could possibly POST the NotificationRule similar to [here](https://github.com/DependencyTrack/frontend/blob/0a4bdcb2e99380f28b2d9b0d178183c70558ab07/src/views/administration/notifications/Alerts.vue#L333-L363) (or just the UUID) and then either build the Notification that satisfies it or send a user provided one.

I think if we can assemble one or more notifications (i.e. one for each enabled `NotificationGroup`) automatically, based on the `NotificationRule`, that would be best.

**Comment by 2000rosser** [comment]
@nscuro I opted for adding `_TEST` to the group in order to get the default pebble format for the notification group, as when using the provided one, it gives errors due to having empty values for the text fields in the json.

Any feedback/ideas on this implementation?

**Comment by nscuro** [comment]
> I opted for adding _TEST to the group in order to get the default pebble format for the notification group, as when using the provided one, it gives errors due to having empty values for the text fields in the json.
>
> Any feedback/ideas on this implementation?

We could alternatively assemble "correct" dummy subjects depending on the group, similar to how we do it in [`AbstractPublisherTest`](https://github.com/DependencyTrack/dependency-track/blob/master/src/test/java/org/dependencytrack/notification/publisher/AbstractPublisherTest.java).

This would avoid the errors you were seeing, and also help with testing custom notification templates.

**Comment by nscuro** [comment]
Looks great @2000rosser! Do you think you can increase the test coverage a bit?

**Comment by 2000rosser** [comment]
@nscuro Thanks! Yeah np

**Review by nscuro — APPROVED** [review]
Thanks!

**Pull request merged**
