### PR TITLE
moving indices to their own initializer

### PR DESCRIPTION
**Pull request by officerNordberg**
Signed-off-by: Drew Thompson <drew.michael.thompson+ghdco@gmail.com>

### Description

Discovered while troubleshooting https://github.com/DependencyTrack/dependency-track/issues/2104

### Addressed Issue

Put reindexing of Lucene Indices after the Event system has been initialized

### Checklist

- [x ] I have read and understand the [contributing guidelines](https://github.com/DependencyTrack/dependency-track/blob/github-templates/CONTRIBUTING.md#pull-requests)
- [ x] This PR fixes a defect, and I have provided tests to verify that the fix is effective
- [ ] This PR implements an enhancement, and I have provided tests to verify that it works as intended
- [ ] This PR introduces changes to the database model, and I have added corresponding [update logic](https://github.com/DependencyTrack/dependency-track/tree/master/src/main/java/org/dependencytrack/upgrade)
- [ ] This PR introduces new or alters existing behavior, and I have updated the [documentation](https://github.com/DependencyTrack/dependency-track/tree/master/docs/_docs) accordingly

### CODE REVIEW

**Comment by officerNordberg** [comment]
@nscuro I don't understand the Codeacy issue.  If someone else can make this fix I'd appreciate it. This project is too hard to  work on.

**Comment by stevespringett** [comment]
@officerNordberg Don't worry about the Codacy issue. @nscuro we should likely remove it since we've moved on to Lift anyway.

**Comment by nscuro** [comment]
Thanks for the PR @officerNordberg!

Looks like it conflicts with #2200. @syalioune, as your PR is a superset of this one, and still a WIP, I'm going to merge this first. Please rebase / merge accordingly.

@stevespringett I have suspended Codacy on the org level.

**Review by nscuro — APPROVED** [review]

**Comment by nscuro** [comment]
@stevespringett Saw just now that the PR targets the 4.6.x branch. Do we want a bugfix release for this?

**Comment by stevespringett** [comment]
@nscuro this should likely go into 4.7

**Comment by officerNordberg** [comment]
Sent it to the wrong place, duplicated @syalioune 's work

**Pull request closed without merging**
