### PR TITLE
allow custom url of 'nvd.nist.gov' mirror

### PR DESCRIPTION
**Pull request by sulegis**
will be useful in some network blocked country
fix bad [pull1146](https://github.com/DependencyTrack/dependency-track/pull/1146)

### CODE REVIEW

**Comment by rgmz** [comment]
@sulegis Would it make sense to allow a custom base URL (`https://nvd.nist.gov/feeds` or `NVD_FEEDS_URL`) instead of individual URLs?

**Comment by sulegis** [comment]
> @sulegis Would it make sense to allow a custom base URL (`https://nvd.nist.gov/feeds` or `NVD_FEEDS_URL`) instead of individual URLs?

commonly, not make sense. BUT，in some network Forbidenned Country(like china), 'nvd.nist.gov' is very slowly and unstable, allow custom will be very Useful.
It's not a issue，but a more flexible way, so we can use [nist-data-mirror](https://github.com/stevespringett/nist-data-mirror) or other tools to across the forbidden.

**Comment by rgmz** [comment]
Oh, I agree that it is useful. I have similar network issues with a company
firewall.

I meant having a single environment variable to use for all URLs, rather
than using a separate environment variable for each feed url.

For example:
```java
private static final String NVD_FEED_URL = System.getenv("NVD_FEED_URL") ==
null ? "https://nvd.nist.gov/feeds/" : System.getenv("NVD_FEED_URL")
private static final String CVE_JSON_11_BASE_META = NVD_FEED_URL +
"json/cve/1.1/nvdcve-1.1-%d.meta"
```

**Comment by sulegis** [comment]
not think a lot. just copy the style of [dependency-check-cli](https://jeremylong.github.io/DependencyCheck/dependency-check-cli/arguments.html), like   --cveUrlModified,  --cveUrlModified,--retireJsUrl. maybe more flexble?
Maybe One BaseURL custom is a Good Idea，it will be more simple.

**Comment by stevespringett** [comment]
Thanks for the PR. Due to external issues such as supporting GitHub advisories and having to configure that, I've made the mirroring support part of that work as well.

In DT v4.4, configuring the NVD will look like this:

Screen Shot 2022-01-26 at 5 09 30 PM

**Pull request closed without merging**
