### PR TITLE
store author field from BOM in database

### PR DESCRIPTION
**Pull request by stephan-wolf-ais**
This fixes issue #1726

### CODE REVIEW

**Review by nscuro — APPROVED** [review]
Thanks for the PR @stephan-wolf-ais! LGTM.

@stevespringett Was the `author` field excluded on purpose up until now?

**Comment by stevespringett** [comment]
> Was the author field excluded on purpose up until now?

No, not excluded on purpose. As the object model for CDX has expanded over time, the fields supported by DT has not kept up. There are other component fields that are also not supported yet.

**Comment by nscuro** [comment]
OK, I filed #1733 for us to take a closer look as to which fields are currently not supported.

I'll merge this PR, however the UI won't show it right now. @stephan-wolf-ais, if you want to see the author in the frontend as well, please submit a PR for the frontend repository as well. Otherwise we'll do it when we tackle #1733.

**Comment by stephan-wolf-ais** [comment]
I will try to make a PR for the frontend as well but it will take some time.

**Pull request merged**
