### PR TITLE
Allow cloning of ACL during Project cloning

### LINKED ISSUE #1534: Cloning a project should optionally clone the ACL
### Current Behavior:
When cloning a project, the ACL for Portfolio Access Control cannot selected to be included in the clone.

### Proposed Behavior:
Allow the ACL to be cloned similar to Properties, Dependencies, Components, Services, Audit History

### PR DESCRIPTION
**Pull request by valentijnscholten**
Adds an `includeACL` parameter to the project clone api. And an extra `/acl/enabled` endpoint for the front-end to query ACL enabled status.

Fixes #1534 and option 1 of #1632

Front-end PR linked below.

Signed-off-by: Valentijn Scholten <valentijnscholten@gmail.com>

### CODE REVIEW

**Comment by valentijnscholten** [comment]
@nscuro Do you want to keep the new `/api/v1/acl/enabled` endpoint in place, even though the front-end doesn't use it anymore?

**Comment by nscuro** [comment]
Let's remove that endpoint. It's hard to keep track of which endpoint is used, best to remove it now.

**Comment by valentijnscholten** [comment]
I'm not sure if it really a requirement that the API can only have methods used by the front-end. 
But my feeling was to keep the endpoint as it might be useful for some clients / scripts to be able to know if ACL is enabled or not. Without needing SYSTEM_CONFIGURATION permissions to query the system configuration properties. But the same could be said of other system properties.

**Comment by nscuro** [comment]
Yeah I get that this could be useful. However, as this information *can* indeed be queried already (as you pointed out, it requires the `SYSTEM_CONFIGURATION` permission), I don't see a reason to have this endpoint right now. 

We can still add it back in if someone really needs it.

**Comment by valentijnscholten** [comment]
OK. Removed. You're bringing down my LOC score today ;-)
Maybe a more generic solution could be implemented in the future if needed. I remember me considering the option to make  part of the config properties available to non-admin users as read-only.

**Comment by nscuro** [comment]
> You're bringing down my LOC score today ;-)

Non-existent code can't have bugs, which is always a win in my book! :p

Anyway, thanks for all your work, it really is appreciated.

**Review by nscuro — APPROVED** [review]

**Pull request merged**
