### PR TITLE
VULNERABILITY.SEVERITY should be updated in database #2474

### PR DESCRIPTION
**Pull request by mge-mm**
### Description

The severity value of a vulnerability is now calculated before creating the vulnerability. With this change, it is impossible that the severity field of a vulnverabilty is null in the database when a vulnerability is created.

This PR added a upgrade script (v4110) which recomputes all database severity values with value NULL of a vulnerability and updates them in the database. This is necessary because there are existing vulnerabilities in the database which have a severity value of NULL. These vulnerabilities are not effected by the changes above and their severity values have to be recalculated separately.

### Addressed Issue

#2474 

### Checklist

- [x] I have read and understand the [contributing guidelines](../CONTRIBUTING.md#pull-requests)
~- [ ] This PR fixes a defect, and I have provided tests to verify that the fix is effective~
~- [ ] This PR implements an enhancement, and I have provided tests to verify that it works as intended~
- [x] This PR introduces changes to the database model, and I have added corresponding [update logic](https://github.com/DependencyTrack/dependency-track/tree/master/src/main/java/org/dependencytrack/upgrade)
~- [ ] This PR introduces new or alters existing behavior, and I have updated the [documentation](https://github.com/DependencyTrack/dependency-track/tree/master/docs/_docs) accordingly~

### CODE REVIEW

**Comment by nscuro** [comment]
Thanks for the PR @mge-mm, I'll get this reviewed over the weekend.

> This PR added a upgrade script (v4110) which recomputes all database severity values with value NULL of a vulnerability and updates them in the database.

Have you tested how long this takes on an instance that has the entire NVD (and / or GitHub Advisories, OSV) mirrored? Because the DB upgrades are executed before health- and liveliness checks are registered, a prolonged upgrade could cause issues with Kubernetes deployments.

**Comment by mge-mm** [comment]
Hello @nscuro, 
I did not test how long it takes explicitly. While testing, the NVD DB mirroring was enabled and i could not recognize any delay in the process. If needed, I can test this again and share the amount of time taken by the DB upgrade.

**Comment by mge-mm** [comment]
Hi @nscuro,
to give you a quick update about 

> Have you tested how long this takes on an instance that has the entire NVD (and / or GitHub Advisories, OSV) mirrored? Because the DB upgrades are executed before health- and liveliness checks are registered, a prolonged upgrade could cause issues with Kubernetes deployments.

It takes about 15 secs to upgrade all Null severities with entire NVD mirrored.

**Comment by nscuro** [comment]
Thanks @mge-mm! Could you perhaps your changes on top of the current `master`? 

I think during commit sign-off there have been some unwanted modifications of unrelated commits, which I'm afraid I cannot merge like this.

**Comment by rkg-mm** [comment]
@nscuro I had to recreate this changes on a new branch. Neither IntelliJ norTortoiseGit was able to reset Marlons branch to a clean state to work from or properly rebase it on the latest master. This was the most buggy rebase i ever saw when I tried :D . Please close this PR and instead check the new PR https://github.com/DependencyTrack/dependency-track/pull/3287.

**Pull request closed without merging**
