### PR TITLE
add DefectDojo "do not reactivate" flag, fixes issue 2424

### PR DESCRIPTION
**Pull request by lme-nca**
### Description

This is a proposed fix for issue: [2424](https://github.com/DependencyTrack/dependency-track/issues/2424) 

### Addressed Issue
https://github.com/DependencyTrack/dependency-track/issues/2424

### Additional Details

This is a simple fix, by adding a new property a User could set the "do not reactivate" flag that is available on the Defectdojo API. This stops the finding from being reactivated in Defectdojo, even if its still available in subsequent scans.

This comes with the downside that a potentially patched vulnerability that is re-introduced by, for example a library downgrade, is reactivated. We could document this edge-case in the Defectdojo sync documentation.

### Checklist

- [x] I have read and understand the [contributing guidelines](../CONTRIBUTING.md#pull-requests)
- [] This PR fixes a defect, and I have provided tests to verify that the fix is effective
- [x] This PR implements an enhancement, and I have provided tests to verify that it works as intended
- [ ] This PR introduces changes to the database model, and I have added corresponding [update logic](https://github.com/DependencyTrack/dependency-track/tree/master/src/main/java/org/dependencytrack/upgrade)
- [ ] This PR introduces new or alters existing behavior, and I have updated the [documentation](https://github.com/DependencyTrack/dependency-track/tree/master/docs/_docs) accordingly

### CODE REVIEW

**Comment by lme-nca** [comment]
Hi @nscuro I have a suggested fix for this issue, do you think this approach is ok ? if so ill go ahead and update documentation and some tests to complete the pull request.

**Comment by nscuro** [comment]
The DD integration is entirely community-maintained, and I do not have a good understanding of how DefectDojo works. Given the discussions that lead to this PR, I think it's fine.

@valentijnscholten Any counterarguments?

**Comment by valentijnscholten** [comment]
LGTM. I would put something like "DefectDojo: " in the PR title to make it more clear, but that's just a detail.

**Review by valentijnscholten — APPROVED** [review]

**Review by nscuro — APPROVED** [review]
Thanks @lme-nca! 🚀

**Pull request merged**
