### PR TITLE
Issue 1932: Empty response on /api/v1/analysis endpoint

### PR DESCRIPTION
**Pull request by kekkegenkai**
Sign-off-by kekkegenkai: kekkegenkai@gmail.com

### Description
The current implementation of the /api/v1/analysis endpoint returns the Statuscode 200 without any content in case no analysis is running/exists.
In this PR I changed this behavior. If no analysis is running the application returns a 404.

### Addressed Issue

#1932 

### Checklist

- [x] I have read and understand the [contributing guidelines](https://github.com/DependencyTrack/dependency-track/blob/github-templates/CONTRIBUTING.md#pull-requests)
- [x] This PR fixes a defect, and I have provided tests to verify that the fix is effective
- [ ] This PR implements an enhancement, and I have provided tests to verify that it works as intended
- [ ] This PR introduces changes to the database model, and I have added corresponding [update logic](https://github.com/DependencyTrack/dependency-track/tree/master/src/main/java/org/dependencytrack/upgrade)
- [ ] This PR introduces new or alters existing behavior, and I have updated the [documentation](https://github.com/DependencyTrack/dependency-track/tree/master/docs/_docs) accordingly

### CODE REVIEW

**Comment by nscuro** [comment]
Thanks for the PR @kekkegenkai! 🚀

Please sign off your commits so the DCO check passes. When you click on the *Details* link of the check, it'll tell you what to do.

**Comment by kekkegenkai** [comment]
Hi @nscuro,

signed off and ready :).

**Comment by nscuro** [comment]
The frontend needed an update to be able to handle this change, I've just gone ahead and did it myself as it is very minor: https://github.com/DependencyTrack/frontend/pull/337

**Review by nscuro — APPROVED** [review]

**Comment by nscuro** [comment]
@kekkegenkai Looks like the `retrieveAnalysisWithoutExistingAnalysisTest` test case needs to be updated as well.

**Comment by kekkegenkai** [comment]
@nscuro sorry for the mess...

**Comment by nscuro** [comment]
No worries @kekkegenkai, thank you for your contribution!

**Pull request merged**
