### PR TITLE
adding PHP/Composer repository support and latest version retrieval

### PR DESCRIPTION
**Pull request by Szasza**
Suggested solution for https://github.com/DependencyTrack/dependency-track/issues/356

I am unsure about what logic should be applied to determining the latest version so for now the `dev-*` and `*-dev` versions are excluded. This can be changed easily if the current implementation in this changeset is a no-go.

Please be aware that this chageset assumes that version `1.0.1` of `cyclonedx-php-composer` is used for BOM generation with the patch https://github.com/CycloneDX/cyclonedx-php-composer/pull/7 in place.

Thank you for taking your time to review this PR, it is much appreciated.

### CODE REVIEW

**Comment by Szasza** [comment]
@stevespringett it seems like there is an issue with the build pipeline configuration, hence the build failure:

```
Run java -jar ~/codacy-coverage-reporter-assembly.jar report -l Java -r target/jacoco-ut/jacoco.xml
10/13 11:41:49 ERROR c.c.rules.ConfigurationRules:22 - Invalid configuration: Empty argument for --project-token 
Error: Process completed with exit code 1.
```

**Comment by stevespringett** [comment]
Thanks for the PR. v4.0 is already feature complete and I'm working on insanely complex upgrade logic. So this PR will be merged in after 4.0 is released. Once 4.0 is released, I'm going to try to get monthly releases out, so 4.1 will quickly follow the release of 4.0.

**Comment by Szasza** [comment]
@stevespringett thank you for the quick feedback and the context, it is much appreciated. I have updated the changeset to reference `4.1.0` instead of `4.0.0` where applicable.

**Comment by Szasza** [comment]
The force-push on the source was me signing my commits, no code changes were introduced.

**Pull request merged**
