### PR TITLE
Update documentation for private vulnerability repository

### LINKED ISSUE #2703: Update docs for private vulnerability repository
### Current Behavior

Current docs published at https://docs.dependencytrack.org/datasources/private-vuln-repo/ are out of date

### Expected Behavior

Content needs to reflect current version of DT

### Dependency-Track Version

4.8.0

### Checklist

- [X] I have read and understand the [contributing guidelines](https://github.com/DependencyTrack/dependency-track/blob/master/CONTRIBUTING.md#filing-issues)
- [X] I have checked the [existing issues](https://github.com/DependencyTrack/dependency-track/issues) for whether this defect was already reported

### PR DESCRIPTION
**Pull request by nscuro**
### Description

This PR updates the documentation for DT's private vulnerability repository feature, as the current documentation is outdated.

It also downgrades `jekyll` to version `3.9.x` again, as GitHub Pages does not yet support Jekyll 4.x yet, according to https://pages.github.com/versions/

### Addressed Issue

Fixes #2703

### Additional Details

N/A

### Checklist

- [x] I have read and understand the [contributing guidelines](../CONTRIBUTING.md#pull-requests)
- ~This PR fixes a defect, and I have provided tests to verify that the fix is effective~
- ~This PR implements an enhancement, and I have provided tests to verify that it works as intended~
- ~This PR introduces changes to the database model, and I have added corresponding [update logic](https://github.com/DependencyTrack/dependency-track/tree/master/src/main/java/org/dependencytrack/upgrade)~
- ~This PR introduces new or alters existing behavior, and I have updated the [documentation](https://github.com/DependencyTrack/dependency-track/tree/master/docs/_docs) accordingly~

### CODE REVIEW

**Review by leec94 — COMMENTED** [review]
The images aren't showing, they show up as links. and when clicking the links they result in a 404. Looks like it may be because the images are in a `docs` folder. If the docs are generated in a different way that might not be an issue. Otherwise, the changes look good, documentation is clear and the images are helpful.

**Review by leec94 — APPROVED** [review]
i was able to run jekyll to view the generated docs, and i can see the images. both content and images look great!

**Comment by leec94** [comment]
after deleting `Gemfile.lock`, running `./dev/scripts/docs-dev-docker.sh` works to generate the documentation as well.

**Comment by nscuro** [comment]
Thanks for the review @leec94!

**Pull request merged**
