### PR TITLE
Update QueryManager.java

### PR DESCRIPTION
**Pull request by japurva1502**
Changed the IncludeVulnerableSoftware Flag to 'True', as Lazy load on vulnerableSoftware is not working for Debian vulnerabilities

### CODE REVIEW

**Comment by nscuro** [comment]
Thanks for the PR @japurva1502! 

Please sign-off your commits. When you click on *Details* of the DCO check, it tells you what to do.

Note: This reverts c277cd0726201e0ada27d2d40689b8ee10ea4d9c (#1765). 

DataNucleus is not lazily fetching the `VulnerableSoftware` associated with the given `Vulnerability`. This may be a behaviour change in DN 6.x, but I need more time to debug.

**Comment by japurva1502** [comment]
Signed off the commits of this PR

**Comment by nscuro** [comment]
I fear I can't reproduce the issue this PR is trying to solve.

I wrote a test that should be able to find occurrences of the issue across the entire portfolio in a running DT instance: https://gist.github.com/nscuro/73b79cfafa8162476dd08cad2a7aea23

I tried with different timings as to when NVD and OSV mirroring are enabled, during different progress states of mirroring for both NVD and OSV, but I can't seem to find any occurrences of this issue. DataNucleus appears to operate as expected.

**Comment by nscuro** [comment]
@japurva1502 Based on our discussion in Slack, I think this PR can be closed for now. Unless we can reproduce this issue, there is no need for this change. Can you confirm and close the PR from your side?

**Comment by japurva1502** [comment]
PR no longer needed..

**Pull request closed without merging**
