### PR TITLE
Fix: Component get deleted in update for Internal Vuln

### PR DESCRIPTION
**Pull request by Gepardgame**
### Description

Now you can update a internal Vulnerability without getting the affected components deleted.

### Addressed Issue

Fixes [#4175](https://github.com/DependencyTrack/dependency-track/issues/4175)

### Additional Details

N/A

### Checklist

- [x] I have read and understand the [contributing guidelines](../CONTRIBUTING.md#pull-requests)
- [x] This PR fixes a defect, and I have provided tests to verify that the fix is effective
~- [ ] This PR implements an enhancement, and I have provided tests to verify that it works as intended~
~- [ ] This PR introduces changes to the database model, and I have added corresponding [update logic](https://github.com/DependencyTrack/dependency-track/tree/master/src/main/java/org/dependencytrack/upgrade)~
~- [ ] This PR introduces new or alters existing behavior, and I have updated the [documentation](https://github.com/DependencyTrack/dependency-track/tree/master/docs/_docs) accordingly~

### CODE REVIEW

**Comment by Gepardgame** [comment]
Again only trivy tests failed.

Is there a way of caching the docker container on the machine which runs the workflow? This would help with not always pulling the image for every test run

**Comment by nscuro** [comment]
Thanks @Gepardgame! Could you please add a test to `VulnerabilityResourceTest` that verifies the desired behavior?

**Comment by Gepardgame** [comment]
I am currently working on it, but have a issue, cause I cannot run the test, cause the Test class starts like this:
`@RunWith(Suite.class)
@SuiteClasses(VulnerabilityQueryManagerTest.SynchronizeVulnerabilityAliasTest.class)
public class VulnerabilityQueryManagerTest extends PersistenceCapableTest {
`
I want to add this test normally to the class, but that doesn't work quit out. @nscuro  Do you know how to fix that?

**Comment by Gepardgame** [comment]
I found a bug in my implementation, but I don't have time anymore today to fix it. I'm sorry, but will do it tomorrow.

**Comment by nscuro** [comment]
No problem @Gepardgame, we can release tomorrow, too.

Worst case I can pick it up, in that case please let me know what bug you found.

**Comment by Gepardgame** [comment]
The bug is that the affectedComponents get duplicated, but without the AffectedVersionAttribution. The original is the same with the AffectedVersionAttribution. In the gui you don't see it, cause it only shows, if there is a AffectedVersionAttribution, but in the spi directly you can see it.

**Comment by nscuro** [comment]
Superseded by #4208

**Pull request closed without merging**
