### PR TITLE
Add the project name and project URL to bom processing notifications

### PR DESCRIPTION
**Pull request by 2000rosser**
### Description
Previously, the user was only notified of the result of the BOM processing.

Now the user is told the name of the project for each notificication, and for processing errors, they are also given the project URL

### Addressed Issue
#3637 

### Additional Details

This change modifies all the bom processing notification rather than just MS Teams ones. Adding the URL to BOM_PROCESSED might also make sense.

### Checklist

- [x] I have read and understand the [contributing guidelines](../CONTRIBUTING.md#pull-requests)
- [ ] This PR fixes a defect, and I have provided tests to verify that the fix is effective
- [x] This PR implements an enhancement, and I have provided tests to verify that it works as intended
- [ ] This PR introduces changes to the database model, and I have added corresponding [update logic](https://github.com/DependencyTrack/dependency-track/tree/master/src/main/java/org/dependencytrack/upgrade)
- [ ] This PR introduces new or alters existing behavior, and I have updated the [documentation](https://github.com/DependencyTrack/dependency-track/tree/master/docs/_docs) accordingly

### CODE REVIEW

**Comment by 2000rosser** [comment]
When I cloned the repo and ran the App, it was using the BomUploadProcessingTask class. I see you also have BomUploadProcessingTaskV2, which is what the unit tests are checking. Which class is the correct one to make the changes?

**Comment by nscuro** [comment]
@2000rosser I don't think you need to touch the code *dispatching* the notification internally at all. The [notification subject](https://github.com/DependencyTrack/dependency-track/blob/7285d90366859dc81f22c21cc821ddb7189672eb/src/main/java/org/dependencytrack/notification/vo/BomProcessingFailed.java#L26-L30) already includes the `project` object, it's just that when transforming this information to the MS Teams Webhook format, it is not included in the output.

When calling `Notification.dispatch`, what happens is that the `Notification` object is sent to [`NotificationRouter`](https://github.com/DependencyTrack/dependency-track/blob/master/src/main/java/org/dependencytrack/notification/NotificationRouter.java), which rules (i.e. the *Alerts* configured in the UI) apply.

For each applicable rule, it will [invoke the corresponding publisher](https://github.com/DependencyTrack/dependency-track/blob/7285d90366859dc81f22c21cc821ddb7189672eb/src/main/java/org/dependencytrack/notification/NotificationRouter.java#L79-L92) (i.e. email, MS Teams, Slack).

`Publisher`s basically use Pebble templates to format a `Notification` to whatever the destination is expecting. You can see the variables made available in the template context here: https://github.com/DependencyTrack/dependency-track/blob/7285d90366859dc81f22c21cc821ddb7189672eb/src/main/java/org/dependencytrack/notification/publisher/Publisher.java#L83-L143

The template files live [here](https://github.com/DependencyTrack/dependency-track/tree/master/src/main/resources/templates/notification/publisher). I recently added a suite of tests that assert the current output of all publishers. The relevant test case for this issue can be found here:

https://github.com/DependencyTrack/dependency-track/blob/7285d90366859dc81f22c21cc821ddb7189672eb/src/test/java/org/dependencytrack/notification/publisher/MsTeamsPublisherTest.java#L71-L107

You will notice that the corresponding test case for the email publisher *does* include the desired information: https://github.com/DependencyTrack/dependency-track/blob/7285d90366859dc81f22c21cc821ddb7189672eb/src/test/java/org/dependencytrack/notification/publisher/SendMailPublisherTest.java#L144-L178

So ideally you shouldn't have to touch any code at all, except the test that is asserting the current output for MS Teams once the template has been updated.

**Comment by 2000rosser** [comment]
@nscuro Thank you for taking the time to explain, it makes a lot more sense now.

**Review by nscuro — APPROVED** [review]
Thanks @2000rosser!

**Pull request merged**
