### PR TITLE
Feature/vulnerable software fuzzy matching

### PR DESCRIPTION
**Pull request by officerNordberg**

### CODE REVIEW

**Review by nscuro — CHANGES_REQUESTED** [review]
Aaaaaaand there's a merge conflict again. Terribly sorry, try rebasing this one with `git pull --rebase` so you're not running in DCO issues again.

We also have to remember making the new property available in the UI here: https://github.com/DependencyTrack/frontend/blob/master/src/views/administration/analyzers/InternalAnalyzer.vue#L5-L10. @officerNordberg, will you raise a PR for that or do you want us to do it?

**Comment by officerNordberg** [comment]
> Aaaaaaand there's a merge conflict again. Terribly sorry, try rebasing this one with `git pull --rebase` so you're not running in DCO issues again.
I would have done the rebase but I had  other commits in my branch from merging master and rebase is a mess.  I didn't trust it and the DCO recommendations seem to warn against it.  Also the @#$@ github UI helpers are crap for DCO.  I can't figure out if I need this https://chrome.google.com/webstore/detail/dco-github-ui/onhgmjhnaeipfgacbglaphlmllkpoijo/related or what the resolution to https://github.com/todogroup/gh-issues/issues/50 was and how to resolve it but it further makes me hate DCO and not understand its value beyond matching two strings which are both email addresses provided by the committer so, what does that prove?   
> 
> We also have to remember making the new property available in the UI here: https://github.com/DependencyTrack/frontend/blob/master/src/views/administration/analyzers/InternalAnalyzer.vue#L5-L10. @officerNordberg, will you raise a PR for that or do you want us to do it?

I didn't know these were being added to the UI, I guess I'd prefer someone else do it as I don't know vue and I barely got it running locally took me too long from the README to figure out npm run serve -- --port 8000 instead of npm run serve

**Comment by officerNordberg** [comment]
@nscuro upon further review I can probably handle submitting that PR until I uncover some other footguns and beartraps

**Comment by nscuro** [comment]
@officerNordberg Cool, let me know if you run into any issues. This may be helpful regarding the port situation: https://github.com/DependencyTrack/dependency-track/blob/master/DEVELOPING.md#debugging-with-frontend

Also, thanks for adding tests!

**Review by nscuro — APPROVED** [review]

**Pull request merged**
