### PR TITLE
fix os handling when trivy sets pkgType on properties

### LINKED ISSUE #3721: Dependency Ttrack makes Trivy-generated SBOM unusable to Trivy server
### Current Behavior

I am trying to use recently added Trivy analyzer but in some cases Dependency Track transforms uploaded SBOM in a way that unables Trivy server to detect OS vulnerabilities correctly (see logs below).
```
trivy_1             | 2024-05-16T11:51:45.145Z  INFO    Detected OS: none
trivy_1             | 2024-05-16T11:51:45.145Z  WARN    unsupported os : none
trivy_1             | 2024-05-16T11:51:45.145Z  INFO    Number of language-specific files: 0
```
When I generate SBOM using Trivy and then specify the same Trivy server that is used by Dependency Track while analyzing then it works correctly:
```
2024-05-16T14:02:41.844+0200    INFO    Detected OS: alpine
2024-05-16T14:02:41.844+0200    INFO    Detecting Alpine vulnerabilities...
2024-05-16T14:02:41.845+0200    INFO    Number of language-specific files: 0
```
When I upload SBOM to Dependency Track either through UI or API then the same SBOM file does not show any vulnerabilities.

### Steps to Reproduce

1.Create SBOM with Trivy. In my case the command is `trivy image --format cyclonedx --output test.json php:7.4.10-fpm-alpine`
2. Upload it to Dependency Track (either using UI or API)
3. In Dependency Track dependencies are correctly listed but no vulnerabilities are shown 

### Expected Behavior

Trivy server correctly parses SBOM uploaded to Dependency Track.

### Dependency-Track Version

4.11.0

### Dependency-Track Distribution

Container Image

### Database Server

PostgreSQL

### Database Server Version

15.0

### Browser

N/A

### Checklist

- [X] I have read and understand the [contributing guidelines](https://github.com/DependencyTrack/dependency-track/blob/master/CONTRIBUTING.md#filing-issues)
- [X] I have checked the [existing issues](https://github.com/DependencyTrack/dependency-track/issues) for whether this defect was already reported

### PR DESCRIPTION
**Pull request by fnxpt**
### Description

Handles PkgType trivy property

### Addressed Issue

Fixes #3721 

### Checklist

- [x] I have read and understand the [contributing guidelines](../CONTRIBUTING.md#pull-requests)
- [x] This PR fixes a defect, and I have provided tests to verify that the fix is effective
- [ ] This PR implements an enhancement, and I have provided tests to verify that it works as intended
- [ ] This PR introduces changes to the database model, and I have added corresponding [update logic](https://github.com/DependencyTrack/dependency-track/tree/master/src/main/java/org/dependencytrack/upgrade)
- [ ] This PR introduces new or alters existing behavior, and I have updated the [documentation](https://github.com/DependencyTrack/dependency-track/tree/master/docs/_docs) accordingly

### CODE REVIEW

**Review by nscuro — COMMENTED** [review]
Thanks @fnxpt! Could you add a test for this in [`TrivyAnalysisTaskIntegrationTest`](https://github.com/DependencyTrack/dependency-track/blob/c04d4dff37ee6676f63bd7b557ee19885a6037d2/src/test/java/org/dependencytrack/tasks/scanners/TrivyAnalysisTaskIntegrationTest.java)?

**Comment by nscuro** [comment]
Please rebase the PR with `master`, then the build should pass.

**Comment by fnxpt** [comment]
rebase seems to have worked, I will add the test later

**Comment by fnxpt** [comment]
@nscuro  Test added

**Review by nscuro — APPROVED** [review]
Thanks @fnxpt for the super fast debugging and fix!

**Pull request merged**
