### PR TITLE
Custom licenses

### PR DESCRIPTION
**Pull request by HagarJNode**
### Description
When uploading CycloneDx created sbom files custom licenses where not matched and updating projects removed manual matched licenses, this is solved here.

### Addressed Issue

Missing custom licenses mapping, as part of this pull:

https://github.com/DependencyTrack/dependency-track/pull/2153

And may be linked to this as well:

https://github.com/DependencyTrack/dependency-track/issues/1211

### Checklist

- [x] I have read and understand the [contributing guidelines](../CONTRIBUTING.md#pull-requests)
- [ ] This PR fixes a defect, and I have provided tests to verify that the fix is effective
- [ ] This PR implements an enhancement, and I have provided tests to verify that it works as intended
- [ ] ~This PR introduces changes to the database model, and I have added corresponding [update logic](https://github.com/DependencyTrack/dependency-track/tree/master/src/main/java/org/dependencytrack/upgrade)~
- [ ] ~This PR introduces new or alters existing behavior, and I have updated the [documentation](https://github.com/DependencyTrack/dependency-track/tree/master/docs/_docs) accordingly~

### CODE REVIEW

**Comment by HagarJNode** [comment]
Damn, I think that the process signing my changes did this. I'll see if I can correct it on Monday.

**Comment by HagarJNode** [comment]
@valentijnscholten looking better now?

**Comment by nscuro** [comment]
@HagarJNode Thanks for the PR! 

Just for my clarification: In custom licenses you can also define a license ID. If the license ID is present in the BOM, the current matching logic should work just fine. In your case, the custom licenses do not have a `license.id` field in your BOM, but only a `license.name`, is that correct?

**Comment by HagarJNode** [comment]
> @HagarJNode Thanks for the PR!
> 
> Just for my clarification: In custom licenses you can also define a license ID. If the license ID is present in the BOM, the current matching logic should work just fine. In your case, the custom licenses do not have a `license.id` field in your BOM, but only a `license.name`, is that correct?

@nscuro - yes, that's very correct.

**Review by nscuro — APPROVED** [review]

**Pull request merged**
