### PR TITLE
Fix component hash policy evaluator

### PR DESCRIPTION
**Pull request by francislance**
### Description

This is for [Component Hash policy condition only supports positive matches #4230](https://github.com/DependencyTrack/dependency-track/issues/4230)

### Addressed Issue

[Component Hash policy condition only supports positive matches #4230](https://github.com/DependencyTrack/dependency-track/issues/4230)

### Additional Details

**Local Testing Screenshots:**

owasp-dt-hash-policy

### Checklist

- [x] I have read and understand the [contributing guidelines](../CONTRIBUTING.md#pull-requests)
- [x] This PR fixes a defect, and I have provided tests to verify that the fix is effective
- [ ] This PR implements an enhancement, and I have provided tests to verify that it works as intended
- [ ] ~This PR introduces changes to the database model, and I have added corresponding [update logic]~(https://github.com/DependencyTrack/dependency-track/tree/master/src/main/java/org/dependencytrack/upgrade)
- [ ] This PR introduces new or alters existing behavior, and I have updated the [documentation](https://github.com/DependencyTrack/dependency-track/tree/master/docs/_docs) accordingly

### CODE REVIEW

**Review by nscuro — CHANGES_REQUESTED** [review]
Thanks @francislance! Could you please add [a test](https://github.com/DependencyTrack/dependency-track/blob/master/src/test/java/org/dependencytrack/policy/ComponentHashPolicyEvaluatorTest.java) for the `IS_NOT` operator?

**Comment by francislance** [comment]
Hi @nscuro yeap the screenshot i attached is actually for IS_NOT testing. Thank you

**Comment by nscuro** [comment]
An automated test in the file I linked would be preferable to ensure we're not breaking this behavior going forward.

**Comment by francislance** [comment]
> An automated test in the file I linked would be preferable to ensure we're not breaking this behavior going forward.

Alright. I will work on it.

**Comment by francislance** [comment]
Hi @nscuro please let me know if you need further actions on my side for this matter. Thank you

**Review by nscuro — APPROVED** [review]
All good, thanks @francislance!

**Pull request merged**
